name: ghanta_gadi
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # Permissions and settings
  open_settings_plus: ^0.4.0
  permission_handler: ^12.0.1
  disable_battery_optimization: ^1.1.2
  flutter_activity_recognition: ^4.0.0

  # State Management
  provider: ^6.1.5+1

  # Utils
  fluttertoast: ^8.2.13
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.5.0

  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  firebase_messaging: ^16.0.1
  cloud_firestore: ^6.0.1
  firebase_database: ^12.0.1
  geoflutterfire_plus: ^0.0.33

  # Google
  googleapis_auth: ^2.0.0
  google_maps_flutter: ^2.13.1

  # Background services
  flutter_background_service: ^5.1.0
  geolocator: ^14.0.2

  #Network
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/svgs/
    - assets/json/
#    - .env

  fonts:
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf